name: ci:v2

on:
  push:
    branches: master
  pull_request:
    paths:
    - '*'
    - 'packages/wPOKT/**'

defaults:
  run:
    working-directory: 'packages/wPOKT'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: test
      run: yarn test
env:
  CI: true
